### ISSUE TITLE
Address cuda warnings and spaCy version warning.

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/DaCy#133]
When running:
```python
import dacy

for model in dacy.models():
    print(model)

dacy_nlp = dacy.load('medium')

doc = dacy_nlp("DaCy er en hurtig og effektiv pipeline til dansk sprogprocessering bygget i SpaCy.")

print('hej')
``` 

I get the following warning:
 
```

da_dacy_small_tft-0.0.0
da_dacy_medium_tft-0.0.0
da_dacy_large_tft-0.0.0
da_dacy_small_trf-0.1.0
da_dacy_medium_trf-0.1.0
da_dacy_large_trf-0.1.0
/venv/lib/python3.9/site-packages/spacy/util.py:833: UserWarning: [W095] Model 'da_dacy_medium_trf' (0.1.0) was trained with spaCy v3.1 and may not be 100% compatible with the current version (3.2.4). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
/venv/lib/python3.9/site-packages/spacy/util.py:833: UserWarning: [W095] Model 'da_dacy_small_trf' (0.1.0) was trained with spaCy v3.1 and may not be 100% compatible with the current version (3.2.4). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
/venv/lib/python3.9/site-packages/spacy_transformers/pipeline_component.py:406: UserWarning: Automatically converting a transformer component from spacy-transformers v1.0 to v1.1+. If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spacy-transformers version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
/venv/lib/python3.9/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/venv/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py:150: UserWarning: [W036] The component 'matcher' does not have any patterns defined.
  matches = self.matcher(doc, allow_missing=True, as_spans=False)
hej
```

Notably this this includes three warning, including SpaCy version, cuda device and matcher object (see also #72) 

*originally version sent to me by mail*

**Note:** While this is a warning there, DaCy still works as intended. The version of spaCy does not influence model performance.

**Comment by EaLindhardt** [comment]
I've tried to download dacy through anaconda, both with pip and conda install and the different ways of installing: https://centre-for-humanities-computing.github.io/DaCy/installation.html

when running

`import dacy`

i get the following

`---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
Input In [14], in <cell line: 1>()
----> 1 import dacy

File ~\AppData\Roaming\Python\Python39\site-packages\dacy\__init__.py:4, in <module>
      1 from dacy.hate_speech import make_offensive_transformer  # noqa
      2 from dacy.sentiment import make_emotion_transformer  # noqa
----> 4 from .about import __download_url__, __title__, __version__  # noqa
      5 from .download import download_model  # noqa
      6 from .load import load, models, where_is_my_dacy

File ~\AppData\Roaming\Python\Python39\site-packages\dacy\about.py:3, in <module>
      1 import pkg_resources
----> 3 __version__ = pkg_resources.get_distribution("dacy").version
      4 __title__ = "dacy"
      5 __download_url__ = "https://github.com/centre-for-humanities-computing/DaCy"

File ~\Anaconda3\lib\site-packages\pkg_resources\__init__.py:477, in get_distribution(dist)
    475     dist = Requirement.parse(dist)
    476 if isinstance(dist, Requirement):
--> 477     dist = get_provider(dist)
    478 if not isinstance(dist, Distribution):
    479     raise TypeError("Expected string, Requirement, or Distribution", dist)

File ~\Anaconda3\lib\site-packages\pkg_resources\__init__.py:353, in get_provider(moduleOrReq)
    351 """Return an IResourceProvider for the named module or requirement"""
    352 if isinstance(moduleOrReq, Requirement):
--> 353     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    354 try:
    355     module = sys.modules[moduleOrReq]

File ~\Anaconda3\lib\site-packages\pkg_resources\__init__.py:897, in WorkingSet.require(self, *requirements)
    888 def require(self, *requirements):
    889     """Ensure that distributions matching `requirements` are activated
    890 
    891     `requirements` must be a string or a (possibly-nested) sequence
   (...)
    895     included, even if they were already activated in this working set.
    896     """
--> 897     needed = self.resolve(parse_requirements(requirements))
    899     for dist in needed:
    900         self.add(dist)

File ~\Anaconda3\lib\site-packages\pkg_resources\__init__.py:788, in WorkingSet.resolve(self, requirements, env, installer, replace_conflicting, extras)
    785 if dist not in req:
    786     # Oops, the "best" so far conflicts with a dependency
    787     dependent_req = required_by[req]
--> 788     raise VersionConflict(dist, req).with_context(dependent_req)
    790 # push the new requirements onto the stack
    791 new_requirements = dist.requires(req.extras)[::-1]

ContextualVersionConflict: (spacy 3.3.1 (c:\users\au576018\anaconda3\lib\site-packages), Requirement.parse('spacy<3.3.0,>=3.2.0'), {'dacy'})`

How do I solve this?

**Comment by KennethEnevoldsen** [comment]
Hi @EaLindhardt, this issue does not seem related to the original post. I will create a new issue with it.
