### ISSUE TITLE
Relax version requirements

### ISSUE THREAD

**Issue by Bonnevie** [centre-for-humanities-computing/DaCy#172]
`dacy` has a very tight version bound on some auxiliary libraries like `protobuf`. It's not apparent why this is required as it does not appear to be a library used internally, but it could of course be intentional. But the version is lagging enough that it is starting to cause compatibility problems with other libraries, so if it can be relaxed that would be very helpful.

**Comment by KennethEnevoldsen** [comment]
Hi @Bonnevie, the protobuf requirement previously stemmed from a error in a downstream package (spacy I believe). It might have been resolved now. I will try see it it can be relaxed or removed.

**Comment by KennethEnevoldsen** [comment]
I have created a pr #174. Assuming everything passes the requirement for protobuf should be removed.

**Comment by KennethEnevoldsen** [comment]
All tests passed and the protobuf dependency is now removed. Thanks for bringing this to my attention!

**Comment by Bonnevie** [comment]
Wow, that was an amazingly swift response, thanks/tak! :)
