### ISSUE TITLE
Relax tqdm version constraint?

### ISSUE THREAD

**Issue by Bonnevie** [centre-for-humanities-computing/DaCy#177]
Hi @KennethEnevoldsen, same problem as with `protobuf`, `tqdm` also seems to be set to a very strict range for a utility - any chance it can be relaxed?

**Comment by KennethEnevoldsen** [comment]
I have created a PR #179 if it passes I will merge it in. This relaxes the lower bound down to what is used by DaNLP. I could probably relax it further so if you need a lower version feel free to create a PR or comment the desired version and then I can see if it works.

**Comment by Bonnevie** [comment]
Hi @KennethEnevoldsen, once again thanks for the quick reply!
My issue is that I need the upper bound increased - packages like e.g. `dvc` have it at `4.63.1` and have had it since June.
Is DaNLP` still being updated?

**Comment by KennethEnevoldsen** [comment]
DaNLP is not being updated, as far as I know. Will update the upper bound as well. Shouldn't be a problem.

**Comment by Bonnevie** [comment]
Thanks again!
