### ISSUE TITLE
Train or fine-tune sentiment model

### ISSUE THREAD

**Issue by mirfan899** [centre-for-humanities-computing/DaCy#184]
There is no documentation and scripts to train the sentiment model.

**Comment by KennethEnevoldsen** [comment]
The sentiment models in DaCy are not trained within DaCy/spaCy (they are either rule-based and implemented in Asent for the best sentiment models available on the Huggingface Hub). I have tried to make this clear in the [documentation](https://centre-for-humanities-computing.github.io/DaCy/using_dacy.sentiment.html) as well:

> currently does not include its own tools for sentiment extraction, but a couple of good tools already exists. DaCy providers wrappers for these to use them in the spaCy/DaCy framework. This allows you to get all of the best models in one place.

You could however train them in spaCy if you have some tagged data following their [guide](https://spacy.io/usage/training). All models trained using spaCy will integrate nicely with DaCy.
