### ISSUE TITLE
 ImportError for lemmy.pipe

### ISSUE THREAD

**Issue by vrunm** [centre-for-humanities-computing/DaCy#200]
I'm trying to use Lemmy as a SpaCy integration following the instructions [here.](https://spacy.io/universe/project/lemmy) However, when I try running import lemmy.pipe I get the error ImportError: cannot import name 'PRON_LEMMA' from 'spacy.symbols' .

I'm using python 3.8 and SpaCy 3.3.0 with the [DaCy pipeline](https://pythonawesome.com/dacy-the-state-of-the-art-danish-nlp-pipeline-using-spacy/).
I am running into this import issue:
`
cannot import name 'PRON_LEMMA' from 'spacy.symbols' (/opt/conda/lib/python3.7/site-packages/spacy/symbols.cpython-37m-x86_64-linux-gnu.so)`

Thank you for you input.

**Comment by KennethEnevoldsen** [comment]
Hi @vrunm, lemmy sadly does not work with spacy 3 or higher. Thus you can't use it with DaCy. I have however considered adding it to DaCy in the future as lemmy it No longer maintained.

**Comment by vrunm** [comment]
Hope it there in the next Version of DaCy.
