### ISSUE TITLE
tft-models?

### ISSUE THREAD

**Issue by emiltj** [centre-for-humanities-computing/DaCy#217]
for model in dacy.models():
    print(model)

Gives:
da_dacy_small_tft-0.0.0
da_dacy_medium_tft-0.0.0
da_dacy_large_tft-0.0.0
da_dacy_small_trf-0.1.0
da_dacy_medium_trf-0.1.0
da_dacy_large_trf-0.1.0

But is not in documentation

**Comment by KennethEnevoldsen** [comment]
It is a mistake, but I don't want to break backward compatibility by renaming them. However have considered simply removing them completely as they are hosted outside of HF and thus required their own maintenance.

**Comment by KennethEnevoldsen** [comment]
(so not temporal fusion transformer models ;) )
