### ISSUE TITLE
Add readability scores functions

### ISSUE THREAD

**Issue by javaberlin** [centre-for-humanities-computing/DaCy#293]
It seems there is no readability tool for processing Danish texts.  I tried with spacy_readability,  loaded a danish language model with it, but it seems that the spacy_readability works with the english language ( it has a hardcoded list of english words in it).

Can Dacy do something similar to spacy_readability ?

Or can Dacy count Danish syllables in a word  ?  That would already be a great help, from there one could implement the readability scores ( flesh-kincaid, etc)

**Comment by KennethEnevoldsen** [comment]
I think you are looking for this tutorial:
https://centre-for-humanities-computing.github.io/DaCy/tutorials/textdescriptives.html

Which uses DaCy in integration with [textdescriptives](https://hlasse.github.io/TextDescriptives/), which calculates readability metrics.

**Comment by javaberlin** [comment]
I

> I think you are looking for this tutorial: https://centre-for-humanities-computing.github.io/DaCy/tutorials/textdescriptives.html
> 
> Which uses DaCy in integration with [textdescriptives](https://hlasse.github.io/TextDescriptives/), which calculates readability metrics.

I am having problems to install compatible versions of spacy, dacy and textdescriptives.  Do you maybe know which versions are compatible ? I tried many combinations,  but there is always something wrong.

Thanks

'''
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy-experimental 0.6.4 requires spacy<3.8.0,>=3.3.0, but you have spacy 3.8.3 which is incompatible.
da-dacy-small-trf 0.2.0 requires spacy<3.6.0,>=3.5.2, but you have spacy 3.8.3 which is incompatible

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
textdescriptives 2.8.0 requires pydantic>=2.0, but you have pydantic 1.10.19 which is incompatible.
textdescriptives 2.8.0 requires spacy[lookups]>=3.6.0, but you have spacy 3.5.3 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
textdescriptives 2.4.0 requires spacy[lookups]<3.5.0,>=3.1.0, but you have spacy 3.5.3 which is incompatible.
Successfully installed spacy-3.5.3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy-transformers 1.2.5 requires spacy<4.0.0,>=3.5.0, but you have spacy 3.4.4 which is incompatible.
da-dacy-small-trf 0.2.0 requires spacy<3.6.0,>=3.5.2, but you have spacy 3.4.4 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
textdescriptives 2.8.2 requires pydantic>=2.0, but you have pydantic 1.10.19 which is incompatible.
da-dacy-small-trf 0.2.0 requires spacy<3.6.0,>=3.5.2, but you have spacy 3.7.5 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
textdescriptives 2.8.2 requires pydantic>=2.0, but you have pydantic 1.10.19 which is incompatible.
textdescriptives 2.8.2 requires spacy[lookups]>=3.6.0, but you have spacy 3.5.2 which is incompatible.


>>> import spacy
>>> import dacy
>>> nlp = dacy.load("small")  # load the latest version of the small model
C:\Users\kh\PycharmProjects\EntropySentiments\.venv39\lib\site-packages\spacy\util.py:910: UserWarning: [W095] Model 'da_dacy_small_trf' (0.2.0) was trained with spaCy v3.5.2 and may not be 100% compatible with the current version (3.8.3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
'''

**Comment by KennethEnevoldsen** [comment]
Hmm on a google colab instance this seems to work without issue:
```py
# install dependencies (if you do this from the terminal remove the !
!pip install dacy textdescriptives
# ...
# dacy-2.7.8 ftfy-6.3.1 pyphen-0.17.0 spacy-alignments-0.9.1 spacy-experimental-0.6.4 spacy-lookups-data-1.0.5 spacy-transformers-1.3.5 spacy-wrap-1.4.5 textdescriptives-2.8.2 tokenizers-0.15.2 transformers-4.36.2

# load model
import dacy
nlp = dacy.load("small")
```

**Comment by javaberlin** [comment]
Thanks ! it works now with 

pip install dacy==2.7.8 ftfy==6.3.1 pyphen==0.17.0 spacy-alignments==0.9.1 spacy-experimental==0.6.4 spacy-lookups-data==1.0.5 spacy-transformers==1.3.5 spacy-wrap==1.4.5 textdescriptives==2.8.2 tokenizers==0.15.2 transformers==4.36.2

**Comment by javaberlin** [comment]
Would it make sense to fine tune you dacy large model to include Riksmaal texts ?  Is that possible , if yes how would one proceed ?  I have about 400 books  (clean, pre-processed, in text form )  that I would like to include in the model - or would it be better to train a model from scratch with those books ?

The features I would need would be  only the Sentiment Analysis ones ( no NER, etc ).

Thank you

**Comment by KennethEnevoldsen** [comment]
well dacy large is a fine-tuned version of the:
danish-foundation-models/encoder-large-v1 (currently not public)

On annotated dataset sources form the danish annotated data. You could indeed further pre-train the model for riksmaal and then fine-tune on the danish annotated data, but it would still require annotated data to fine-tune it for riksmaal.

Do you have that?

**Comment by javaberlin** [comment]
> well dacy large is a fine-tuned version of the: danish-foundation-models/encoder-large-v1 (currently not public)
> 
> On annotated dataset sources form the danish annotated data. You could indeed further pre-train the model for riksmaal and then fine-tune on the danish annotated data, but it would still require annotated data to fine-tune it for riksmaal.
> 
> Do you have that?

No I do not have it .  What would such an annotated file from that corpus look like ?  Is there another way , I mean using less pipelines - I would need the sentencizer,  and  sentiment analyser .  There is a big corpus of Norwegian resources at https://ai.nb.no/datasets/   , but I did not find information there  about the annotations. 

Anyway I will write some researchers at the National Library of Norway,  asking if they have annotated data for the 18th century.

**Comment by KennethEnevoldsen** [comment]
I don't believe such annotations are common and as far as I know they don't exist. Do you have your data publicly available?

**Comment by javaberlin** [comment]
I uploaded the 366 books I have to a github repo, granted you access to it .  The books are in text format, UTF-8 encoded.    

https://github.com/javaberlin/norwegian_literature

Could that help ?

**Comment by KennethEnevoldsen** [comment]
> I might be able to make something reasonable if so. However would require ~250 samples or so to evaluate the model (more if you want the evaluation to be better).

This would still be a requirement.

However you could try using:

https://github.com/explosion/spacy-llm

**Comment by javaberlin** [comment]
> > I might be able to make something reasonable if so. However would require ~250 samples or so to evaluate the model (more if you want the evaluation to be better).
> 
> This would still be a requirement.
> 
> However you could try using:
> 
> https://github.com/explosion/spacy-llm

So I think I misunderstood the requirements .... You mean I need at least 250  labeled samples, is it like that ?

By the documentation in the page https://spacy.io/api/large-language-models#sentiment   it seems they work with scores, from 0 to 1.0 ( using  spacy.Sentiment.v1 )
```
- text: 'This is horrifying.'
  score: 0
- text: 'This is underwhelming.'
  score: 0.25
- text: 'This is ok.'
  score: 0.5
- text: "I'm looking forward to this!"
  score: 1.0
```

But Dacy uses 8 sentiments , so the training file (for [spacy.TextCat.v1](https://spacy.io/api/large-language-models#textcat-v1) would look like below, is it right ?

```json
[
  {
    "text": "Over det hele Landskab hvilede et Præg af dyb Fred og af stille Liv, men også af den mest trøstesløse Eensomhed",
    "answer": "grief/sadness"
  },
  {
    "text": "Præstekonen vimsede frem og tilbage medens Præsten underholdt mig om sine Annexreiser.",
    "answer": "aversion/reluctance"
  },
  {
    "text": "Maden var alt færdig og på Bordet, Værtinden på Gløder for at den skulde blive kold.",
    "answer": "anxiety/worry"
  },
  {
    "text": " For, Liighed holder vi meget af, der mumles stærkt om, at en vis Mands Huus kneiser så høit over andres, at der seer så aristocratisk ud, man tænker så uformærkt på at jævne det med de øvrige Huuse, så bliver Gaden så kiøn, liige; seer han, lille Leonard.",
    "answer": "anger/irritation"
  }
]

```

**Comment by KennethEnevoldsen** [comment]
> So I think I misunderstood the requirements .... You mean I need at least 250 labeled samples, is it like that ?

Yes indeed.

**Comment by KennethEnevoldsen** [comment]
> But Dacy uses 8 sentiments , so the training file (for [spacy.TextCat.v1](https://spacy.io/api/large-language-models#textcat-v1) would look like below, is it right ?

Ahh so you are looking for emotion classification. I still believe you can use the spacy.llm for this task. from their docs:

```py
import spacy

nlp = spacy.blank("en")
llm = nlp.add_pipe("llm_textcat")
llm.add_label("INSULT")
llm.add_label("COMPLIMENT")
doc = nlp("You look gorgeous!")
print(doc.cats)
# {"COMPLIMENT": 1.0, "INSULT": 0.0}
```

**Comment by javaberlin** [comment]
Ok I think I will stick to your Dacy implementation.  It seems to do well for those Rikmaal books ( at least for the sentiment analysis part).    I added a threshold of 0.9  for the probs  when processing the results ,so that only emotions that reached that threshold are considered valid.  

About 84% of the sentences in the whole corpus are recognized as "emotional", and from those about 37% reach the threshold.

The ones that did not reach the threshold are either mixed sentiments sentences and sentences with the dominant emotion having less than 90% probability.

I am using the frequency distribution of the sentiments in  the sentences to assign a dominant emotion to a book - considering only the dominant sentiment in each sentence.

Thank you for your help !
