### ISSUE TITLE
Augmentation

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/DaCy#4]
- [x] Entity augmentation
   - [x] Gender augmentation (awareness of gender)
   - [x] Second order person augmentation (Lastname, Firstname)
   - [ ] Usernames (autogenerates e.g. WhiteTruffle101 or Kenneth Enevoldsen -> KennethEnevoldsen)
- [ ] Mispellings Augmentations, se e.g. [this repo](https://github.com/ybisk/charNMT-noise)
  - [x] Keystroke error based on keyboard distance
- [ ] Historic augmentations
  - [x]   æ->ae, å -> aa (and a), ø->oe 
  - [ ] uppercasing of nouns
- [ ] Social media
  - [ ] Adding hashtags augmentation
- [ ] Others, potentially see this [tweet](https://twitter.com/omarsar0/status/1391729605766262785?s=20) or this [kaggle summary](https://neptune.ai/blog/data-augmentation-nlp)

**Comment by martincjespersen** [comment]
- [ ] Add entity augmentation for abbreviated first names e.g., Martin Jespersen -> M. Jespersen or Jespersen, M.

**Comment by KennethEnevoldsen** [comment]
Hei @martincjespersen entity augmentation has just been added in the 1.0.0 update. I recommend you check out the documentation for [robustness and biases in Danish NLP models](https://centre-for-humanities-computing.github.io/DaCy/robustness.html). There will also be a paper coming out soon (probably Monday) I will make sure to send it your way. Parts of this work have very much been inspired by your fairness benchmark 🙏 -  so I very much hope you find the results interesting.

**Comment by KennethEnevoldsen** [comment]
As seen in issue #59 augmenters will be replaced with using the augmenty package. 

@martincjespersen you might be especially interested in this project. It is still under development, but already looking very promising.
