### ISSUE TITLE
Add table with model parameters, layers etc. in the training markdown

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/DaCy#64]

**Comment by mirfan899** [comment]
any update on this????

**Comment by KennethEnevoldsen** [comment]
Currently, there are plans for adding it in. It is known which models are used for DaCy, and one can then inspect the respective models for their number of parameters, layers etc.. For many models in spacy, these numbers are quite arbitrary (trainable parameters in a tok2vec model using word embedding are not the same as the number in a transformer model).

However, I would be very open to alternative views on this - especially if there is certain use cases where this information is useful.
