### ISSUE TITLE
User configurable cache dir

### ISSUE THREAD

**Issue by dhpollack** [centre-for-humanities-computing/DaCy#68]
I would like to configure the cache dir with an environmental variable instead of using the default `~/.dacy`.  This is a relatively simple change, but it useful if you want the cache to be in a known place (i.e. a specific folder in a docker image).  I created a PR for this feature (#67).   Some projects like to have associated issues so I am creating an issue as well.

**Comment by KennethEnevoldsen** [comment]
Thanks again for this PR, it has now been added in version `1.2.0` in PR #70 (which includes PR #67 ).
