### ISSUE TITLE
requirement versions too strict

### ISSUE THREAD

**Issue by dhpollack** [centre-for-humanities-computing/DaCy#75]
## Description
The versions specified for some requirements are too strict.  Specifically, I am trying to install DaCy with [dvc](https://dvc.org/) and got an error that the versions of `tqdm` are incompatible.  For `tqdm` specifically, I don't think you need to specify a version because it's pretty hard to break it and it's a requirement way upstream.  But as an example, I would use the smallest minor version that you want to the next major version, which is [how spacy does it](https://github.com/explosion/spaCy/blob/master/requirements.txt#L18).  I would do this with `pandas` as well.

## Your Environment
* DaCy Version Used: 1.2
* Operating System: linux
* Environment Information:  installing with dvc (but this will happen quite a bit)

**Comment by KennethEnevoldsen** [comment]
Thanks, @dhpollack, have created a PR (#77 ), will merge it once the test pass. I have removed the tqdm requirement (as it is a part of spaCy so no need to specify it twice), Similarly, I have loosened the requirements for pandas to the next major version.
