### ISSUE TITLE
Add Tutorials: "Extracting text statistics and readability metrics using DaCy and Textdescriptives"

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/DaCy#88]
After removing readability it would be nice with a tutorial on: "Extracting text statistics and readability metrics using DaCy and Textdescriptives"

Potentially using the packages to describe the examining the language complexity between conversational data and legal documents on DAGW or a similar task using a publicly available dataset.

**Comment by HLasse** [comment]
Yeah, we can basically just copy paste the one from TextDescriptives but change spacy model to dacy. I'll take a look later today/early next week

**Comment by KennethEnevoldsen** [comment]
That is perfect!
